### PR TITLE
Update get_common_data

### PR DESCRIPTION
**Pull request by adrianvrj**
Update the get_common_data function in the https://github.com/walnuthq/starkflare-indexer backend repo to include a new field in the response called top_transactions_by_steps

Closes issue https://github.com/walnuthq/starkflare/issues/7

### CODE REVIEW

**Review by barabanovro — CHANGES_REQUESTED** [review]
Thanks for your contribution! The account_calls table may have duplicate tx_hash values, but the get_top_transactions_by_steps function should return distinct transactions. Please merge the latest changes from the main branch into your feature branch. Then, create a new migration script starting with 004_ for this change instead of modifying existing migration scripts. Look at https://github.com/walnuthq/starkflare-indexer/pull/3/files as a reference

**Review by barabanovro — CHANGES_REQUESTED** [review]
As a best practice, avoid modifying existing migration scripts. Instead, focus on updating the get_common_data function within your new migration script. For reference, take a look at this example PR: https://github.com/walnuthq/starkflare-indexer/pull/3/files

**Review by barabanovro — CHANGES_REQUESTED** [review]
In the current implementation, transactions are sorted by tx_hash instead of the number of steps, please fix it. Example output of the current implementation:
```json
"top_transactions_by_steps": [
    {
      "tx_hash": "0x00003c8c3364c775d3e74fc07e96c5792ef13cf1b81ae148067970b822db48aa",
      "steps_consumed": 173742,
      "tx_timestamp": 1716910371,
      "block_number": 644352
    },
    {
      "tx_hash": "0x000041d00a0fe13ffefe5994803eef79edfe43a264c96d3038825f3b63fee69d",
      "steps_consumed": 45149,
      "tx_timestamp": 1716895727,
      "block_number": 644312
    },
    {
      "tx_hash": "0x000052a9c16872caecf2281d366a6635a3aa59186cb104f3af6362745f82e086",
      "steps_consumed": 77337,
      "tx_timestamp": 1716934295,
      "block_number": 644419
    },
    {
      "tx_hash": "0x00005dc5f97c849a7742c1b28a428757f776faaa48d6a0391095732aa0b1187e",
      "steps_consumed": 33279,
      "tx_timestamp": 1716920441,
      "block_number": 644380
    },
    {
      "tx_hash": "0x00006de5718a16589a65597ea7748d273f9c3eeae58941339114c8b0cda45b47",
      "steps_consumed": 22348,
      "tx_timestamp": 1716921179,
      "block_number": 644382
    },
    {
      "tx_hash": "0x00007e1b8947baf8559ace69366cc95f0f3eee24e6110ffb9cfd360de40f3103",
      "steps_consumed": 1529586,
      "tx_timestamp": 1716941277,
      "block_number": 644438
    },
    {
      "tx_hash": "0x00008751f361f80263e1b7fc75dc614657d6aff321c98c61a4c418dd0cb8679a",
      "steps_consumed": 25334,
      "tx_timestamp": 1716923285,
      "block_number": 644389
    },
    {
      "tx_hash": "0x00008c6ddc5930f94758996fb9f52d227cc012a551db00b94f22a746b711a234",
      "steps_consumed": 9072,
      "tx_timestamp": 1716933913,
      "block_number": 644418
    },
    {
      "tx_hash": "0x00009a9e3ae852878f83f36e1be60addff7889e0d0c511293291929fa1756a27",
      "steps_consumed": 10795,
      "tx_timestamp": 1716893124,
      "block_number": 644305
    },
    {
      "tx_hash": "0x0000a7b534ba09f576c5dfa4698fd7485bd4b69c4f22bbb1097bf54521002c8c",
      "steps_consumed": 102753,
      "tx_timestamp": 1716891397,
      "block_number": 644300
    }
  ]
```

**Comment by jaipaljadeja** [comment]
LGTM!

**Review by barabanovro — APPROVED** [review]

**Pull request merged**
